### ISSUE TITLE
Round 2 comments and suggestions

### ISSUE THREAD

**Issue by rfazeli** [kiranrawat/Detecting-Fake-News-On-Social-Media#3]
Your work looks great so far. Here is my feedback:

**General Suggestions**
1. You're missing two packages in `requirements.txt`. They're `flask` and `flask_bootstrap`
2. You don't need to keep the `.py` versions of your notebooks in a separate `scripts/` folder. You can keep them in the same `notebooks/` folder. In your `scripts/` folder (it might be better to rename it to `src/` ) you want to have your refactored versions of your notebooks. We can discuss this further, but essentially you want three python scripts (1. preprocess.py or transform.py 2. train.py and 3. inference.py) that would contain relevant functionality that you've already developed in your notebooks.

**Specific Comments**
1. You should move this block of code outside the `predict()` function (i.e. can move it to line 12). Because right now the two `.pkl` files would have to be loaded every time you call `predict()`. But if you move it to the top the loadings will only happen once when you initially start the app. It might not make a lot of difference in your case but if you have to load a large model every time it would increase your prediction time.
https://github.com/kiranrawat/Detecting-Fake-News-On-Social-Media/blob/f390409db09931075ec4beef3d0e343749f3e8ed/app.py#L19-L23

**Comment by kiranrawat** [comment]
closing the issue.
